language: java
sudo: false

jdk:
  - oraclejdk11
  - oraclejdk8
  - openjdk7

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    - secure: OdSIcNSjG1/GVBSejmM5Y4AQTIw0+b7lYWO4dmRBCqyvNiJDTRn+LZHPrWQpJZ0bqu0R6kGpsa0xkK91V55apS2e41reo9wXJGBjVySaAVgy8tqZfWvlN89UeXTknrji07zpJFV/lFrNHpQkkmOIHt9FCn4UB/YRxigPSayl8B8=
    - secure: Nuj4/iyROkt13DUgmBt55RZ7bLn9yBDSTm+TagWV5JuTFXse3fPhiqNtKftelA0pwxfD9M1zdjRb8rpeanlKFQkrf2l3fOhk12Hs6SZrKAROi4XJrKZs78ouUIS45dOSHo/FXoE3H3xZ8UNp3BAL+3Wwq3R9XwuJ81Jhxq5Pb/0=
